---@alias AirAttacksChildType
--- | 'Interceptors'
--- | 'LightGunships'
--- | 'Bombers'
--- | 
--- | 'TorpedoBombers'
--- | 'GuidedMissiles'
--- | 'Gunships'
--- | 'CombatFighters'
--- | 
--- | 'StratBombers'
--- | 'AirSuperiority'
--- | 'HeavyGunships'
--- | 'HeavyTorpedoBombers'